### PR TITLE
Support for multiple bridges and bridge discovery in admin panel

### PR DESCRIPTION
**Pull request by Zefau**
Hi there,

thanks for your adapter. I have addressed and fixed my issue (https://github.com/smaragdschlange/ioBroker.nuki/issues/9).
Furthermore, I have implemented some more features as stated in the title. Also I have re-aligned the states.

I would appreciate a merge.

Kind regards,
Zefau

### CODE REVIEW

**Comment by smaragdschlange** [comment]
Hi Zefau,
I'd like to merge your pull request. But AppVeyor shows an error on Node.js 4 support. I don't mind dropping Node.js 4 support, but do you know how to exclude the test for it in AppVeyor?

Greetings,
Sven

**Comment by smaragdschlange** [comment]
Hi Zefau,
I really want to merge but there are a lot of checks with Travis CI and AppVeyor that are failing when I initiate the merge. Any ideas what went wrong?

Sven

**Comment by smaragdschlange** [comment]
Hi again,
thank you for all your work on the adapter. I've found the reason for the trouble I had merging and running your version. There have been some conflicts that I tried to resolve but accidently left some of the conflict markers in the coding. I was not aware that this is actually changing your fork, so I really have to appologize to you. I don't know how to correct this in your fork, so maybe you could do that. Just search for the string 'master' in the files main.js and index_m.html and delete it (2x in each file). 
Again, I'm really sorry!

Now for some other concerns I have about your version of the adapter:
After I corrected my silly mistake in a local copy of your repository I still had problems to start an instance, because the two dependencies nuki-api and nuki-bridge-api did not install automatically. I had to install the nuki-bridge-api manually on the server (which apparently then installed nuki-api, too). Afterwards the bridge discovery worked like a charm and the instance (with the API token) found my Nukis and created the objects. 
Unfortunately there seems to be something wrong with the connection to the bridge:
Log:

`nuki.0 | 2019-01-21 12:35:44.904 | debug | Error: socket hang up
-- | -- | -- | --
nuki.0 | 2019-01-21 12:35:38.542 | debug | system.adapter.admin.0: logging true
nuki.0 | 2019-01-21 12:35:35.203 | debug | 503 - "HTTP 503 Unavailable"
nuki.0 | 2019-01-21 12:35:35.203 | warn | Connection settings for bridge incorret with ID 1836069522! No connection established.
nuki.0 | 2019-01-21 12:35:34.920 | info | Listening for Nuki events on port 51988.
nuki.0 | 2019-01-21 12:35:34.896 | info | Retrieving Nuki's from Bridge 192.168.178.66..
nuki.0 | 2019-01-21 12:35:34.894 | info | No API token provided.
nuki.0 | 2019-01-21 12:35:34.890 | info | starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.nuki, node: v8.12.0
nuki.0 | 2019-01-21 12:35:34.775 | debug | statesDB connected
nuki.0 | 2019-01-21 12:35:34.738 | debug | objectDB connected
host.tinkerboard_s | 2019-01-21 12:35:33.520 | info | instance system.adapter.nuki.0 started with pid 24682`

I know I have not been very responsive recently, but I work on this adapter only once in a while when I have some spare time. I'm pretty sure I could learn a lot from you about Java/node.js development since I'm quite new to node.js, guthub and npm. And these are the reasons I have to take baby steps with this adapter. You did a lot of (re)work in your version and I think it became a whole new adapter. If I did this merge (after the mentioned problems got sorted out) this adapter would become virtually unmaintainable for me because right now I can't follow all the changes made in this pull request.
My suggestion is that we might keep the two forks separated for now. This adapter is a rather simple one that I'm still able to handle. I would still love to implement your improvements in baby steps (like, for instance your fix for issue #9 ) so I can understand what's going on and still be able to maintain the adapter later on.
I really hope I didn't offend you and we will be able to figure out how to get your improvements into this development. 
Of course, you are welcome to publish your version on npm and ioBroker if I'm to slow for you ;-)

**Comment by Zefau** [comment]
Hi,

thanks for your feedback and don't worry about the changes to my fork. I will restore them from my local copy.

Cheers,
Zefau

**Pull request closed without merging**
